### ISSUE TITLE
Unable to execute raw queries

### ISSUE THREAD

**Issue by jsdhasfedssad** [ly4k/BloodHound#1]
Hi,

Using your fork of Bloodhound 4.2.0 I am unable to execute raw queries. Pressing Enter inputs a new line instead of executing the query. I expect pressing Enter to execute the query as it does in the official branch.

Thanks!

**Comment by ly4k** [comment]
Hello @jsdhasfedssad 

As the placeholder _should_ indicate, you'll need to press ctrl+enter. This allows for subqueries.
